### ISSUE TITLE
boil algorithm has low accuracy

### ISSUE THREAD

**Issue by susuxnj** [dchiji-ntt/meta-ticket#1]
Can I ask you a question, why the boil algorithm has such a low accuracy when I just run the code? Do I need to tune hyperparameters

**Comment by dchiji-ntt** [comment]
Thank you for your question! Which experiment caused the problem? The hyperparameters for BOIL are set to be the same as MAML in our experiments, following the [BOIL paper](https://arxiv.org/abs/2008.08882).

**Comment by susuxnj** [comment]
Thank you for your work. I have solved my problem by modifying the config.yaml, The lr of the trained hyperparameters was null and was modified to 0.006.

**Comment by dchiji-ntt** [comment]
PS. If you want to reproduce our experiments, `parallel` command should be useful because it automatically sets hyperparameters for each experiment!

**Comment by susuxnj** [comment]
I see. Thank you very much
